name: ie-bank-empty-rg

on:
  push:
    paths:
      - 'scripts/**' # Trigger only with changes under folder 'scripts'
  schedule:
    - cron: '59 21 * * *' # Trigger at 23:59 CEST (UTC + 2) every day
  workflow_dispatch: # Trigger manually

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  RESOURCE_GROUP_RETAKERS: BCSAI2024-DEVOPS-RETAKERS-DEV
  RESOURCE_GROUP_PROFFESSORS: BCSAI2024-DEVOPS-PROFESSORS
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b

jobs:
  remove-resource-groups:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
    - uses: actions/checkout@main
    
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true 

      # Empty resource group students dev
    - name: empty-resource-group-dev
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_DEV }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"

      # Empty resource group students uat
    - name: empty-resource-group-dev
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_UAT }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"

      # Empty resource group students prod
    - name: empty-resource-group-prod
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_PROD }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"

    # Empty resource group students retakers
    - name: empty-resource-group-retakers
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_RETAKERS }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"

    # Empty resource group students proffessors
    - name: empty-resource-group-proffessors
      uses: azure/powershell@v1
      with:
          inlineScript: ./scripts/empty-resource-group -ResourceGroupName "${{ env.RESOURCE_GROUP_PROFFESSORS }}" -SubscriptionId "${{ env.SUBSCRIPTION_ID_DEV }} "
          azPSVersion: "latest"